# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LikelihoodCV <- function(S, Tob, TB, SigmaHat1, k, SigmaHat2, RestrictionMatrix, restrictions) {
    .Call('_svars_LikelihoodCV', PACKAGE = 'svars', S, Tob, TB, SigmaHat1, k, SigmaHat2, RestrictionMatrix, restrictions)
}

nlmCV <- function(S, Tob, TB, SigmaHat1, k, SigmaHat2, RestrictionMatrix, restrictions) {
    .Call('_svars_nlmCV', PACKAGE = 'svars', S, Tob, TB, SigmaHat1, k, SigmaHat2, RestrictionMatrix, restrictions)
}

IdentifyVolatility <- function(crit, u, TB, p, k, RestrictionMatrix, restrictions, Tob, SigmaHat1, SigmaHat2, Zt, y, maxIter) {
    .Call('_svars_IdentifyVolatility', PACKAGE = 'svars', crit, u, TB, p, k, RestrictionMatrix, restrictions, Tob, SigmaHat1, SigmaHat2, Zt, y, maxIter)
}

LikelihoodGARCHu <- function(parameter, est, Sigma1, Tob) {
    .Call('_svars_LikelihoodGARCHu', PACKAGE = 'svars', parameter, est, Sigma1, Tob)
}

nlmGARCHu <- function(parameter, est, Sigma1, Tob) {
    .Call('_svars_nlmGARCHu', PACKAGE = 'svars', parameter, est, Sigma1, Tob)
}

SigmaGARCHuniv <- function(param, Tob, SigmaE, est) {
    .Call('_svars_SigmaGARCHuniv', PACKAGE = 'svars', param, Tob, SigmaE, est)
}

GarchStart <- function(StartIter, k, ste, Tob) {
    .Call('_svars_GarchStart', PACKAGE = 'svars', StartIter, k, ste, Tob)
}

LikelihoodGARCHm <- function(parameter, SigmaE, Tob, k, u, RestrictionMatrix, restrictions) {
    .Call('_svars_LikelihoodGARCHm', PACKAGE = 'svars', parameter, SigmaE, Tob, k, u, RestrictionMatrix, restrictions)
}

nlmGARCHm <- function(parameter, SigmaE, Tob, k, u, RestrictionMatrix, restrictions) {
    .Call('_svars_nlmGARCHm', PACKAGE = 'svars', parameter, SigmaE, Tob, k, u, RestrictionMatrix, restrictions)
}

GARCHiterativeP <- function(parameter, SigmaUniv, k, parameterIniu, u, RestrictionMatrix, restrictions, maxIter, Tob, crit) {
    .Call('_svars_GARCHiterativeP', PACKAGE = 'svars', parameter, SigmaUniv, k, parameterIniu, u, RestrictionMatrix, restrictions, maxIter, Tob, crit)
}

LikelihoodNGMLStage2 <- function(theta, u, Tob, k, RestrictionMatrix, restrictions) {
    .Call('_svars_LikelihoodNGMLStage2', PACKAGE = 'svars', theta, u, Tob, k, RestrictionMatrix, restrictions)
}

LikelihoodNGMLStage3 <- function(A, Z_t, Y, B_stand_est, sigma_est, d_freedom, k, Tob) {
    .Call('_svars_LikelihoodNGMLStage3', PACKAGE = 'svars', A, Z_t, Y, B_stand_est, sigma_est, d_freedom, k, Tob)
}

LikelihoodST <- function(parameter, Tob, u, k, G, RestrictionMatrix, restrictions) {
    .Call('_svars_LikelihoodST', PACKAGE = 'svars', parameter, Tob, u, k, G, RestrictionMatrix, restrictions)
}

nlmST <- function(S, Tob, u, k, transition, RestrictionMatrix, restrictions) {
    .Call('_svars_nlmST', PACKAGE = 'svars', S, Tob, u, k, transition, RestrictionMatrix, restrictions)
}

mGLSst <- function(transition, B, Lambda, Z_t, k, Y) {
    .Call('_svars_mGLSst', PACKAGE = 'svars', transition, B, Lambda, Z_t, k, Y)
}

IterativeSmoothTransition <- function(transition, u, Tob, k, p, crit, maxIter, Z_t, Yloop, RestrictionMatrix, restrictions) {
    .Call('_svars_IterativeSmoothTransition', PACKAGE = 'svars', transition, u, Tob, k, p, crit, maxIter, Z_t, Yloop, RestrictionMatrix, restrictions)
}

YLagCr <- function(y, p) {
    .Call('_svars_YLagCr', PACKAGE = 'svars', y, p)
}

