# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LikelihoodCV <- function(S, Tob, TB, SigmaHat1, k, SigmaHat2, RestrictionMatrix, restrictions) {
    .Call('_svars_LikelihoodCV', PACKAGE = 'svars', S, Tob, TB, SigmaHat1, k, SigmaHat2, RestrictionMatrix, restrictions)
}

nlmCV <- function(S, Tob, TB, SigmaHat1, k, SigmaHat2, RestrictionMatrix, restrictions) {
    .Call('_svars_nlmCV', PACKAGE = 'svars', S, Tob, TB, SigmaHat1, k, SigmaHat2, RestrictionMatrix, restrictions)
}

IdentifyVolatility <- function(crit, u, TB, p, k, RestrictionMatrix, restrictions, Tob, SigmaHat1, SigmaHat2, Zt, y, maxIter) {
    .Call('_svars_IdentifyVolatility', PACKAGE = 'svars', crit, u, TB, p, k, RestrictionMatrix, restrictions, Tob, SigmaHat1, SigmaHat2, Zt, y, maxIter)
}

LikelihoodNGMLStage2 <- function(theta, u, il, Tob, k, rows, RestrictionMatrix, restrictions) {
    .Call('_svars_LikelihoodNGMLStage2', PACKAGE = 'svars', theta, u, il, Tob, k, rows, RestrictionMatrix, restrictions)
}

LikelihoodST <- function(parameter, Tob, u, k, G, RestrictionMatrix, restrictions) {
    .Call('_svars_LikelihoodST', PACKAGE = 'svars', parameter, Tob, u, k, G, RestrictionMatrix, restrictions)
}

nlmST <- function(S, Tob, u, k, transition, RestrictionMatrix, restrictions) {
    .Call('_svars_nlmST', PACKAGE = 'svars', S, Tob, u, k, transition, RestrictionMatrix, restrictions)
}

mGLSst <- function(transition, B, Lambda, Z_t, k, Y) {
    .Call('_svars_mGLSst', PACKAGE = 'svars', transition, B, Lambda, Z_t, k, Y)
}

IterativeSmoothTransition <- function(transition, u, Tob, k, p, crit, maxIter, Z_t, Yloop, RestrictionMatrix, restrictions) {
    .Call('_svars_IterativeSmoothTransition', PACKAGE = 'svars', transition, u, Tob, k, p, crit, maxIter, Z_t, Yloop, RestrictionMatrix, restrictions)
}

