# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LikelihoodCV <- function(S, Tob, TB, Sigma_hat1, k, Sigma_hat2, RestrictionMatrix, restrictions) {
    .Call('_svars_LikelihoodCV', PACKAGE = 'svars', S, Tob, TB, Sigma_hat1, k, Sigma_hat2, RestrictionMatrix, restrictions)
}

IdentifyVolatilityNew <- function(counter, Bhat, LambdaHat, Exit, crit, MaxIter, Zt, TB, y, p, k, RestrictionMatrix, restrictions, S, Tob) {
    .Call('_svars_IdentifyVolatilityNew', PACKAGE = 'svars', counter, Bhat, LambdaHat, Exit, crit, MaxIter, Zt, TB, y, p, k, RestrictionMatrix, restrictions, S, Tob)
}

LikelihoodST <- function(parameter, Tob, u, k, G, RestrictionMatrix, restrictions) {
    .Call('_svars_LikelihoodST', PACKAGE = 'svars', parameter, Tob, u, k, G, RestrictionMatrix, restrictions)
}

nlmST <- function(S, Tob, u, k, transition, RestrictionMatrix, restrictions) {
    .Call('_svars_nlmST', PACKAGE = 'svars', S, Tob, u, k, transition, RestrictionMatrix, restrictions)
}

mGLSst <- function(transition, B, Lambda, Z_t, k, Y) {
    .Call('_svars_mGLSst', PACKAGE = 'svars', transition, B, Lambda, Z_t, k, Y)
}

IterativeSmoothTransition <- function(transition, u, Y, Tob, k, p, crit, maxIter, Z_t, Yloop, RestrictionMatrix, restrictions) {
    .Call('_svars_IterativeSmoothTransition', PACKAGE = 'svars', transition, u, Y, Tob, k, p, crit, maxIter, Z_t, Yloop, RestrictionMatrix, restrictions)
}

